{
 "title": "Weather",
 "time": { "from": "now/w", "to": "now/w" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Forecast",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Apparent temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"apparentTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Precipitation probability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"precipitation_probability\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"visibility\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uvIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"windDirection\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"windSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cloud cover",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cloudCover\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Showers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"showers\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Daily", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"maxTemperature\" or r[\"_field\"] == \"minTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Apparent temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"minApparentTemperature\" or r[\"_field\"] == \"maxApparentTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Sunrise & sunset",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sunrise\" or r[\"_field\"] == \"sunset\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uvIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\" or r[\"_field\"] == \"precipitation_hours\" or r[\"_field\"] == \"precipitation_probability_max\" or r[\"_field\"] == \"showers\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dominantWindDirection\" or r[\"_field\"] == \"maxWindSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Hourly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"apparentTemperature\" or r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\" or r[\"_field\"] == \"showers\" or r[\"_field\"] == \"precipitation_probability\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cloud cover",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cloudCover\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "UV Index & Visibility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"visibility\" or r[\"_field\"] == \"uvIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Wind speed & wind direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hourly_weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"windDirection\" or r[\"_field\"] == \"windSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}